// Typed API client. Types come from src/types (generated by `make types`).
//
// Fixture mode (VITE_USE_FIXTURES=true, or `npm run dev:fixtures`) serves responses from the
// repo's /fixtures directory so UI work never blocks on the backend. Otherwise requests go to
// /api, which the Vite dev server proxies to the backend on :8000.
//
// Skeleton (F-5): only the JSON endpoints the Capture -> Build flow needs. Voice, projects and
// exports are added by the tasks that own them (VOX, FE-11, FE-10).
import type {
  EditRequest,
  EditResponse,
  GenerateRequest,
  GenerateResponse,
  HealthResponse,
  InstructionsRequest,
  InstructionsResponse,
  ParseResponse,
  TemplateInfo,
} from "../types";

export const USE_FIXTURES =
  import.meta.env.VITE_USE_FIXTURES === "true" || import.meta.env.MODE === "fixtures";

export class ApiError extends Error {
  constructor(
    readonly status: number,
    readonly code: string,
    message: string,
  ) {
    super(message);
  }
}

async function readJson<T>(res: Response): Promise<T> {
  if (!res.ok) {
    const body = await res.json().catch(() => null);
    throw new ApiError(res.status, body?.error?.code ?? `HTTP_${res.status}`, body?.error?.message ?? res.statusText);
  }
  return res.json() as Promise<T>;
}

const getJson = <T>(url: string) => fetch(url).then((res) => readJson<T>(res));

const postJson = <T>(url: string, body: unknown) =>
  fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }).then((res) =>
    readJson<T>(res),
  );

const fixture = <T>(path: string) => getJson<T>(`/fixtures/${path}`);

// Mirrors the backend's F-4 stub: the layout param alone picks the fixture.
const rampFixture = (layout: unknown) =>
  fixture<GenerateResponse>(layout === "switchback" ? "specs/ramp_switchback.json" : "specs/ramp_straight.json");

export const api = {
  health: (): Promise<HealthResponse> =>
    USE_FIXTURES ? Promise.resolve({ ok: true, version: "fixtures" }) : getJson("/api/health"),

  templates: (): Promise<TemplateInfo[]> => (USE_FIXTURES ? fixture("templates.json") : getJson("/api/templates")),

  parse: async (image: File, measurements?: unknown, note?: string): Promise<ParseResponse> => {
    if (USE_FIXTURES) {
      const { spec } = await rampFixture("straight");
      return {
        spec: { ...spec, parts: [], rule_checks: [] },
        template_confidence: null,
        questions: [],
        raw_notes: "Fixture response: the image was not analyzed.",
      };
    }
    const form = new FormData();
    form.append("image", image);
    if (measurements !== undefined) form.append("measurements", JSON.stringify(measurements));
    if (note) form.append("note", note);
    return readJson(await fetch("/api/parse", { method: "POST", body: form }));
  },

  generate: async (req: GenerateRequest): Promise<GenerateResponse> =>
    USE_FIXTURES ? rampFixture(req.params.layout?.value) : postJson("/api/generate", req),

  edit: async (req: EditRequest): Promise<EditResponse> => {
    if (!USE_FIXTURES) return postJson("/api/edit", req);
    const { spec, plan } = await rampFixture(req.spec.params.layout?.value);
    return { spec, plan, patch: {}, message: "Fixture mode: the edit was not applied.", needs_clarification: false };
  },

  instructions: (req: InstructionsRequest): Promise<InstructionsResponse> =>
    USE_FIXTURES ? fixture("instructions/ramp_switchback.json") : postJson("/api/instructions", req),
};
