/* GENERATED by `make types` from shared/schema/contracts.schema.json. Do not edit by hand. */

export interface SketchBuildContracts {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "BuildStep".
 */
export interface BuildStep {
  cut_callouts: CutCallout[];
  n: number;
  part_labels: string[];
  safety_tip: string | null;
  text: string;
  title: string;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "CutCallout".
 */
export interface CutCallout {
  label: string;
  spoken: string;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "CutListRow".
 */
export interface CutListRow {
  actual_dims: string;
  cut_notes: string[];
  label: string;
  length_display: string;
  length_in: number;
  material: string;
  name: string;
  part_ids: string[];
  qty: number;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "EditRequest".
 */
export interface EditRequest {
  spec: Spec;
  utterance: string;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "Spec".
 */
export interface Spec {
  assumed: string[];
  meta: {
    [k: string]: unknown;
  };
  params: {
    [k: string]: ParamValue;
  };
  parts: Part[];
  rule_checks: RuleCheck[];
  schema_version: "1.0";
  template: string;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "ParamValue".
 */
export interface ParamValue {
  confidence: number | null;
  source: "read" | "inferred" | "default" | "user";
  value: number | string | boolean;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "Part".
 */
export interface Part {
  cut_notes: string[];
  group: string | null;
  id: string;
  label: string;
  material: string;
  name: string;
  profile: [number, number][];
  thickness: number;
  transform: Transform;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "Transform".
 */
export interface Transform {
  /**
   * @minItems 3
   * @maxItems 3
   */
  pos: [number, number, number];
  /**
   * @minItems 3
   * @maxItems 3
   */
  rot: [number, number, number];
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "RuleCheck".
 */
export interface RuleCheck {
  detail: string;
  fix: RuleFix | null;
  id: string;
  source_ref: string;
  status: "pass" | "warn" | "fail" | "info";
  title: string;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "RuleFix".
 */
export interface RuleFix {
  label: string;
  params_patch: {
    [k: string]: unknown;
  };
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "EditResponse".
 */
export interface EditResponse {
  message: string;
  needs_clarification: boolean;
  patch: {
    [k: string]: unknown;
  };
  plan: Plan;
  spec: Spec;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "Plan".
 */
export interface Plan {
  contractor_quote: number | null;
  cut_list: CutListRow[];
  has_placeholder_prices: boolean;
  layouts: StockLayout[];
  savings: number | null;
  shopping: ShoppingItem[];
  subtotal: number;
  tax: number;
  total: number;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "StockLayout".
 */
export interface StockLayout {
  kind: "board" | "sheet";
  length_in: number;
  material: string;
  pieces: PlacedPiece[];
  stock_id: string;
  utilization: number;
  width_in: number;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "PlacedPiece".
 */
export interface PlacedPiece {
  h: number;
  label: string;
  part_id: string;
  rotated: boolean;
  w: number;
  x: number;
  y: number;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "ShoppingItem".
 */
export interface ShoppingItem {
  description: string;
  key: string;
  qty: number;
  source_url: string | null;
  subtotal: number;
  unit: string;
  unit_price: number;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "ErrorBody".
 */
export interface ErrorBody {
  code: string;
  message: string;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "ErrorResponse".
 */
export interface ErrorResponse {
  error: ErrorBody;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "ExportRequest".
 */
export interface ExportRequest {
  spec: Spec;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "GenerateRequest".
 */
export interface GenerateRequest {
  meta: {
    [k: string]: unknown;
  };
  params: {
    [k: string]: ParamValue;
  };
  template: string;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "GenerateResponse".
 */
export interface GenerateResponse {
  plan: Plan;
  spec: Spec;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "HealthResponse".
 */
export interface HealthResponse {
  ok: boolean;
  version: string;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "InstructionsRequest".
 */
export interface InstructionsRequest {
  spec: Spec;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "InstructionsResponse".
 */
export interface InstructionsResponse {
  steps: BuildStep[];
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "ParseResponse".
 */
export interface ParseResponse {
  questions: string[];
  raw_notes: string;
  spec: Spec | null;
  template_confidence: number | null;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "ProjectCreateRequest".
 */
export interface ProjectCreateRequest {
  name: string;
  spec: Spec;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "ProjectCreateResponse".
 */
export interface ProjectCreateResponse {
  id: number;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "ProjectDetail".
 */
export interface ProjectDetail {
  id: number;
  latest: Spec;
  name: string;
  versions: VersionInfo[];
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "VersionInfo".
 */
export interface VersionInfo {
  created_at: string;
  n: number;
  source: "parse" | "edit" | "manual" | "fix";
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "ProjectSummary".
 */
export interface ProjectSummary {
  id: number;
  name: string;
  template: string;
  thumb: string | null;
  updated_at: string;
}
/**
 * One step of a template's deterministic build outline (input to /instructions).
 *
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "SkeletonStep".
 */
export interface SkeletonStep {
  action_key: string;
  part_labels: string[];
  phase: string;
  title: string;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "SttResponse".
 */
export interface SttResponse {
  text: string;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "TemplateInfo".
 */
export interface TemplateInfo {
  defaults: {
    [k: string]: unknown;
  };
  description: string;
  key: string;
  name: string;
  params_schema: {
    [k: string]: unknown;
  };
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "TtsRequest".
 */
export interface TtsRequest {
  text: string;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "VersionCreateRequest".
 */
export interface VersionCreateRequest {
  source: "parse" | "edit" | "manual" | "fix";
  spec: Spec;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "VersionCreateResponse".
 */
export interface VersionCreateResponse {
  n: number;
}
/**
 * This interface was referenced by `SketchBuildContracts`'s JSON-Schema
 * via the `definition` "VersionResponse".
 */
export interface VersionResponse {
  spec: Spec;
}
