// Generates frontend/src/types/index.ts from shared/schema/contracts.schema.json.
// Run via `make types` (which regenerates the JSON Schema from the Pydantic models first).
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const schemaPath = resolve(here, "../../shared/schema/contracts.schema.json");
const outPath = resolve(here, "../src/types/index.ts");

const schema = JSON.parse(await readFile(schemaPath, "utf8"));

// json-schema-to-typescript only understands the draft-07 tuple form (`items: [...]`), not 2020-12
// `prefixItems`, which would turn every tuple (pos, rot, profile points) into `unknown`. The shared
// schema stays valid 2020-12; we convert only in memory here.
function tuplesToDraft07(node) {
  if (Array.isArray(node)) {
    node.forEach(tuplesToDraft07);
  } else if (node && typeof node === "object") {
    if (Array.isArray(node.prefixItems)) {
      node.items = node.prefixItems;
      node.additionalItems = false;
      delete node.prefixItems;
    }
    Object.values(node).forEach(tuplesToDraft07);
  }
}
tuplesToDraft07(schema);

const ts = await compile(schema, "SketchBuildContracts", {
  // The schema is just a bag of $defs, so emit every definition.
  unreachableDefinitions: true,
  additionalProperties: false,
  bannerComment:
    "/* GENERATED by `make types` from shared/schema/contracts.schema.json. Do not edit by hand. */",
  style: { singleQuote: false },
});

await mkdir(dirname(outPath), { recursive: true });
// Normalize to LF so output is identical on Windows and Linux.
await writeFile(outPath, ts.replace(/\r\n/g, "\n"), "utf8");
console.log(`wrote ${outPath}`);
